# SpaceX Data Pipeline

In [2]:
import pandas as pd
import spacex_api as api

In [5]:
df = api.get_spacex_data()

[2024-11-12 20:08:08,947][INFO] Fetching data from SpaceX API
[2024-11-12 20:08:09,461][INFO] Data fetched successfully

In [4]:
df.head()

,fairings,links,static_fire_date_utc,static_fire_date_unix,net,window,rocket,success,failures,details,...,date_utc,date_unix,date_local,date_precision,upcoming,cores,auto_update,tbd,launch_library_id,id
0,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,2006-03-17T00:00:00.000Z,1.142554e+09,False,0.0,5e9d0d95eda69955f709d1eb,0.0,"[{'time': 33, 'altitude': None, 'reason': 'mer...",Engine failure at 33 seconds and loss of vehicle,...,2006-03-24T22:30:00.000Z,1143239400,2006-03-25T10:30:00+12:00,hour,False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",True,False,None,5eb87cd9ffd86e000604b32a
1,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,0.0,"[{'time': 301, 'altitude': 289, 'reason': 'har...",Successful first stage burn and transition to ...,...,2007-03-21T01:10:00.000Z,1174439400,2007-03-21T13:10:00+12:00,hour,False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",True,False,None,5eb87cdaffd86e000604b32b
2,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,0.0,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",Residual stage 1 thrust led to collision betwe...,...,2008-08-03T03:34:00.000Z,1217734440,2008-08-03T15:34:00+12:00,hour,False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",True,False,None,5eb87cdbffd86e000604b32c
3,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,2008-09-20T00:00:00.000Z,1.221869e+09,False,0.0,5e9d0d95eda69955f709d1eb,1.0,[],Ratsat was carried to orbit on the first succe...,...,2008-09-28T23:15:00.000Z,1222643700,2008-09-28T11:15:00+12:00,hour,False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",True,False,None,5eb87cdbffd86e000604b32d
4,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,1.0,[],None,...,2009-07-13T03:35:00.000Z,1247456100,2009-07-13T15:35:00+12:00,hour,False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",True,False,None,5eb87cdcffd86e000604b32e

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 27 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   fairings               169 non-null    object
 1   links                  205 non-null    object
 2   static_fire_date_utc   121 non-null    object
 3   static_fire_date_unix  121 non-null    float64
 4   net                    205 non-null    bool
 5   window                 117 non-null    float64
 6   rocket                 205 non-null    object
 7   success                186 non-null    object
 8   failures               205 non-null    object
 9   details                134 non-null    object
 10  crew                   205 non-null    object
 11  ships                  205 non-null    object
 12  capsules               205 non-null    object
 13  payloads               205 non-null    object
 14  launchpad              205 non-null    object
 15  flight_number          205 non-null    int64
 16  name                   205 non-null    object
 17  date_utc               205 non-null    object
 18  date_unix              205 non-null    int64
 19  date_local             205 non-null    object
 20  date_precision         205 non-null    object
 21  upcoming               205 non-null    bool
 22  cores                  205 non-null    object
 23  auto_update            205 non-null    bool
 24  tbd                    205 non-null    bool
 25  launch_library_id      72 non-null     object
 26  id                     205 non-null    object
dtypes: bool(4), float64(2), int64(2), object(19)
memory usage: 37.8+ KB

In [6]:
df.columns

Index(['fairings', 'links', 'static_fire_date_utc', 'static_fire_date_unix',
       'net', 'window', 'rocket', 'success', 'failures', 'details', 'crew',
       'ships', 'capsules', 'payloads', 'launchpad', 'flight_number', 'name',
       'date_utc', 'date_unix', 'date_local', 'date_precision', 'upcoming',
       'cores', 'auto_update', 'tbd', 'launch_library_id', 'id'],
      dtype='object')

In [7]:
df.dtypes

fairings                  object
links                     object
static_fire_date_utc      object
static_fire_date_unix    float64
net                         bool
window                   float64
rocket                    object
success                  float64
failures                  object
details                   object
crew                      object
ships                     object
capsules                  object
payloads                  object
launchpad                 object
flight_number              int64
name                      object
date_utc                  object
date_unix                  int64
date_local                object
date_precision            object
upcoming                    bool
cores                     object
auto_update                 bool
tbd                         bool
launch_library_id         object
id                        object
dtype: object